# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20161105_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
